import { InfoType } from "./types/info";

export const INFO_LIST: InfoType[] = [
  {
    date: "2023-03-17 금요일",
    productName: "피피티 만능사냥꾼",
    invoiceNo: "23412321",
    sender: "이규호",
    receiver: "김재한",
    deliver: "신현식",
    state: "ready",
    company: "CJ대한통운 (민락동)",
  },
  {
    date: "2023-03-20 금요일",
    productName: "반팔티",
    invoiceNo: "23412322",
    sender: "이규호",
    receiver: "김재한",
    deliver: "신현식",
    state: "start",
    company: "롯데택배",
  },
  {
    date: "2023-03-30 금요일",
    productName: "긴팔티",
    invoiceNo: "23412323",
    sender: "이규호",
    receiver: "김재한",
    deliver: "신현식",
    state: "done",
    company: "로젠택배",
  },
  {
    date: "2023-03-17 금요일",
    productName: "반바지",
    invoiceNo: "23412324",
    sender: "이규호",
    receiver: "김재한",
    deliver: "신현식",
    state: "start",
    company: "쿠팡",
  },
  {
    date: "2023-03-17 금요일",
    productName: "피피티 만능사냥꾼",
    invoiceNo: "23412325",
    sender: "이규호",
    receiver: "김재한",
    deliver: "신현식",
    state: "ready",
    company: "CJ대한통운 (민락동)",
  },
  {
    date: "2023-03-17 금요일",
    productName: "피피티 만능사냥꾼",
    invoiceNo: "23412326",
    sender: "이규호",
    receiver: "김재한",
    deliver: "신현식",
    state: "ready",
    company: "CJ대한통운 (민락동)",
  },
  {
    date: "2023-03-17 금요일",
    productName: "피피티 만능사냥꾼",
    invoiceNo: "23412327",
    sender: "이규호",
    receiver: "김재한",
    deliver: "신현식",
    state: "ready",
    company: "CJ대한통운 (민락동)",
  },
  {
    date: "2023-03-17 금요일",
    productName: "피피티 만능사냥꾼",
    invoiceNo: "23412328",
    sender: "이규호",
    receiver: "김재한",
    deliver: "신현식",
    state: "ready",
    company: "CJ대한통운 (민락동)",
  },
  {
    date: "2023-03-17 금요일",
    productName: "피피티 만능사냥꾼",
    invoiceNo: "23412329",
    sender: "이규호",
    receiver: "김재한",
    deliver: "신현식",
    state: "ready",
    company: "CJ대한통운 (민락동)",
  },
  {
    date: "2023-03-17 금요일",
    productName: "피피티 만능사냥꾼",
    invoiceNo: "234123210",
    sender: "이규호",
    receiver: "김재한",
    deliver: "신현식",
    state: "ready",
    company: "CJ대한통운 (민락동)",
  },
];
